services:
  node-backend:
    build: ./node-backend
    ports:
      - "3000:3000"
    env_file:
      - node-backend/.env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
